- hosts: localhost
  tasks:
    - user:
        name: zane
        comment: "Zane Cooper"
        uid: 1000
        groups: sudo,docker
    - user:
        name: aaron
        comment: "Aaron Culich"
        uid: 1001
        groups: sudo,docker
    - user:
        name: nebres
        comment: "Aaron Nebres"
        uid: 1002
        groups: sudo,docker
    - user:
        name: chench
        comment: "Chris Hench"
        uid: 1004
        groups: sudo,docker
    - user:
        name: tony
        comment: "Tony Cricelli"
        uid: 1005
        groups: sudo,docker
    - user:
        name: usha
        comment: "Usha Manandhar"
        uid: 1006
        groups: sudo,docker
    - user:
        name: rylo
        comment: "Ryan Lovett"
        uid: 1007
        groups: sudo,docker
    - authorized_key:
        user: zane
        state: present
        key: https://github.com/zcooper.keys
    - authorized_key:
        user: aaron
        state: present
        key: https://github.com/aculich.keys
    # - authorized_key:
    #     user: nebres
    #     state: present
    #     key: https://github.com/zzz-get-from-nebres.keys
    - authorized_key:
        user: chench
        state: present
        key: https://github.com/henchc.keys
    - authorized_key:
        user: tony
        state: present
        key: https://github.com/Montereytony.keys
    - authorized_key:
        user: usha
        state: present
        key: https://github.com/ushamanandhar.keys
    - authorized_key:
        user: rylo
        state: present
        key: https://github.com/ryanlovett.keys










